#define _POSIX_C_SOURCE 200112L

#include "alloc.h"
#include "vendor/src/alloc.c"
#include "vendor/src/get_changed_ranges.c"
#include "vendor/src/language.c"
#include "vendor/src/lexer.c"
#include "vendor/src/node.c"
#include "vendor/src/parser.c"
#include "vendor/src/query.c"
#include "vendor/src/stack.c"
#include "vendor/src/subtree.c"
#include "vendor/src/tree_cursor.c"
#include "vendor/src/tree.c"
#include "vendor/src/wasm.c"
